# meteor-shower configuration file for load testing
loadtest:
  # Target domain
  domain: "http://localhost:8080"
  
  # Endpoints with weights
  # Weight determines the distribution of requests across endpoints
  endpoints:
    - path: "/"
      weight: 1.0
  
  # Example: Multiple endpoints with different weights
  # endpoints:
  #   - path: "/"
  #     weight: 1.0      # Highest frequency
  #   - path: "/health"
  #     weight: 0.5      # Medium frequency
  #   - path: "/slow"
  #     weight: 0.2      # Lowest frequency
  
  # Requests per second
  rps: 10
  
  # Number of concurrent clients
  concurrency: 1
  
  # Test duration in seconds
  duration: 10
  
  # Output format (html or json)
  output: "html"
